### ISSUE TITLE
Dans les classes JavaFX FXML et Controllers, décidez de la convention de dénomination des variables et du fx:id

### ISSUE THREAD

**Issue by T1WiLLi** [T1WiLLi/CMS#40]
# Conventions de nommage pour les classes FXML et Contrôleurs JavaFX

## Variables et Méthodes

Pour les variables et méthodes dans les classes Contrôleur, suivez les conventions de nommage Java :

- Variables : `camelCase` (ex. : `prenom`, `adresseEmail`)
- Méthodes : `camelCase` (ex. : `calculerTotal()`)

## fx:id dans les fichiers FXML

Pour le `fx:id` dans les fichiers FXML, il existe différentes conventions et pratiques :

1. **Préfixe avec le type de contrôle** :
   - Dans FXML : `<Button fx:id="btnSoumettre" ...>`
   - Dans le Contrôleur : `@FXML private Button btnSoumettre;`

2. **Utiliser camelCase sans préfixe de type de contrôle (recommandé)** :
   - Dans FXML : `<Button fx:id="boutonSoumettre" ...>`
   - Dans le Contrôleur : `@FXML private Button boutonSoumettre;`

3. **Utiliser camelCase avec un nom descriptif** :
   - Dans FXML : `<Button fx:id="boutonEnregistrerModifications" ...>`
   - Dans le Contrôleur : `@FXML private Button boutonEnregistrerModifications;`

Choisissez une convention et soyez cohérent dans tout le projet.

Example de mauvais code (pris de la branche Sam) : 

![Capture d’écran 2024-05-29 002729](https://github.com/T1WiLLi/CMS/assets/48188781/b0857c91-e8ee-49d6-855d-b24a886ec225)

**Comment by Ap0llonn** [comment]
d
